media:
  input: static/images
  output: /images

content:
  - name: blog
    label: Blog
    type: collection
    path: content/blog
    format: yaml-frontmatter
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: summary
        label: Resume
        type: text
      - name: body
        label: Contenu
        type: rich-text
    view:
      fields: [title, date, tags]
      primary: title
      sort: [date]
